### ISSUE TITLE
[Bug]:    not display the icons for commands in the second and later rows(mobile v1.14.16)

### ISSUE THREAD

**Issue by Akiyam-hub** [phibr0/obsidian-commander#107]
### Describe the bug

I updated to mobile v1.14.16

Currently, the commander's custom toolbar does not display the icons for commands in the second and later rows
![Screenshot_20231014-070653](https://github.com/phibr0/obsidian-commander/assets/53425804/d3ae0a00-e0eb-43b6-b2dc-e757109d6574)

### Steps to reproduce

I have tried the following with no improvement

Restarting the plugin
Restarting the application

### Operating system

Android

**Comment by ribber** [comment]
I have this issue too

**Comment by hkw1831** [comment]
Same on iOS. Probably due to the new release v1.4.16 contains the following:

- iOS: Added new persistent "Hide keyboard" button to the mobile toolbar.

**Comment by brimwats** [comment]
Affects android as well

**Comment by hkw1831** [comment]
Did some analysis:

Found that after obsidian is upgraded, the html tag in mobile-toolbar is one level indent: from `<div class="mobile-toolbar-options-container ">` -> `<div class="mobile-toolbar-option">` to `<div class="mobile-toolbar-options-container">` -> `<div class="mobile-toolbar-options-list">` -> `<div class="mobile-toolbar-option">`

Left hand side: before upgrade. Right hand side: after upgrade.

![image](https://github.com/phibr0/obsidian-commander/assets/18748745/c77fab5b-6989-461e-98b2-a07e4a6f1fa0)

Hence replacing `.mobile-toolbar-options-container` to `.mobile-toolbar-options-list` in styles/advanced-toolbar.scss should be able to display icons in multiple rows.


To remove the "Hide keyboard" button in iOS, as `<div class="mobile-toolbar-floating-options">`  containing the button which is a child of `<div class="mobile-toolbar-options-list">`. Adding `.mobile-toolbar-floating-options {display:none}` in some css file should work.

**Comment by Bojji-git** [comment]
Same here. I'm on Android 11

**Comment by XQZmeSIR** [comment]
> > .mobile-toolbar-options-container to .mobile-toolbar-options-list styles/advanced-toolbar.scss should be able to display icons in multiple rows.
> 
> Oh! I tried its steps. It works the same way on Android. ![Screenshot_20231016-163431](https://user-images.githubusercontent.com/53425804/275427071-3f508c42-0d1d-4cc0-bbfa-62393f0b459b.jpeg)

Can you elaborate on the solution a little bit? Where should we make these changes?
Because II added ‘.mobile-toolbar-floating-options {display:none}’ in CSS but multiple rows still don’t work. I am on IOS.

**Comment by ChasKane** [comment]
This is nuking my ability to use Obsidian on android. On that device, I downloaded a generic text editing app and tried replacing `.mobile-toolbar-options-container` with `.mobile-toolbar-options-list` in `.obsidian/plugins/obsidian-commander/styles.css` but that didn't fix the issue. I assumed `styles/advanced-toolbar.scss` is compiled to `styles.css`, no?

@Akiyam-hub did you fork, modify, and recompile this repo and transfer it to your phone?

**Comment by hkw1831** [comment]
This is my only changes. Hope it helps.

https://gist.github.com/hkw1831/2c7176cd0ff024724f9c812f706d503c

**Comment by fsover2** [comment]
> This is my only changes. Hope it helps.
> 
> https://gist.github.com/hkw1831/2c7176cd0ff024724f9c812f706d503c

This worked for me on Android. Thanks!

**Comment by marshes** [comment]
> This is my only changes. Hope it helps.
> 
> https://gist.github.com/hkw1831/2c7176cd0ff024724f9c812f706d503c

Can confirm these three long lines also fix it on iOS. I saved the line locally as a txt file and then imported them to my vault using a Shortcut. Definitely a pain to add custom css to iOS but doable.

**Comment by Bojji-git** [comment]
> \u003Cdiv

Where can I find this file so that I perform the changes?

**Comment by marshes** [comment]
An alternate place that the css file can be placed for iOS (and presumably Android is `/<vaultname>/.obsidian/snippets/mobileToolbarFix.css` and then you can turn the file on in the bottom of the appearance settings in Obsidian within the css snippets section. 

Adding the vault name directory in Taibo as an Added Location is new to me and a great find! Makes it pretty easy to do. (Thanks for that one)

**Comment by Bojji-git** [comment]
> > > \u003Cdiv
> > 
> > Where can I find this file so that I perform the changes?
> 
> A few messages up, you see: ` .obsidian/plugins/cmdr/styles.css`.  
> Make a copy of this file, like `styles.css.bak` and create a new one with the lines in the gist linked above, save it as `styles.css` and save it (in the cmdr folder).  
> You can do this on a PC if you have synced to your desktop or laptop or you can do it on your mobile as well, with some text editor. I mentioned Taio for iOS.

Many thanks! Managed to do it.

**Comment by Bojji-git** [comment]
> > > \u003Cdiv
> > 
> > Where can I find this file so that I perform the changes?
> 
> A few messages up, you see: ` .obsidian/plugins/cmdr/styles.css`.  
> Make a copy of this file, like `styles.css.bak` and create a new one with the lines in the gist linked above, save it as `styles.css` and save it (in the cmdr folder).  
> You can do this on a PC if you have synced to your desktop or laptop or you can do it on your mobile as well, with some text editor. I mentioned Taio for iOS.

Many thanks! Managed to do it. Copied the .css file and then renamed the extension to .md. Opened the file via Obsidian, deleted everything, then pasted the gist text onto it. Rerenamed to .css extension. Moved the file onto the cmdr folder, and the toolbar was back to work as expected.

**Comment by rcherny** [comment]
Is there anyone that can open a pull request with this fix? I can’t before this weekend at the earliest…

**Comment by superjangooo** [comment]
Amazing work, thanks for fixing it and sharing your solution!

**Comment by stevesup** [comment]
Thanks for this fix. Works great!

**Comment by duch11** [comment]
Thanks!

**Comment by drannex42** [comment]
I submitted the PR #111 for this, new update has been merged and the issue appears to be fixed — make sure to update your day extension in Obsidian!
