### ISSUE TITLE
Allow use of all Lucide icons or emojis for icons

### ISSUE THREAD

**Issue by realfr** [phibr0/obsidian-commander#119]
### Describe the feature

- Enable all available Lucide icons, this way after browsing, I can just search for the icon on the plugin and have it available.
- Expand the choice of icons to something that can be browsed on any computer or mobile phone like emojis. I can browse for the appropriate emoji and then just apply it using the plugin.

### Does this fix a problem? If so, specify.

The only way to find an appropriate icon is to keep typing words that might potentially match an icon available from the plugin. This can take ages. The icons are only searchable via their names on Lucide.

### Did you consider other alternatives?

An alternative way of finding an icon would be to go to [Lucide](https://lucide.dev/). What's very frustrating with this workflow is that once I've found an icon, it is often not available on the plugin.

**Comment by purierca** [comment]
HUGE request on my side, to me that's the only thing that's missing

**Comment by jcesguerram** [comment]
Agreed! More icons would be great.
If you could add for example 'H1', 'H2' etc icons for header commands that would be awesome

**Comment by erazlogo** [comment]
+1 on this request. I have my own script to create a new kanban board, and I'd love to assign the icon Obsidian Kanban uses for the Ribbon to my script, but it is not available in Commander :( Thank you!

**Comment by O-RONI** [comment]
+1 on this request!

In the meantime, I managed to use some of the other Lucide icons by manually putting them in the data.json file in the plugin directory. But this would be 100% better...

**Comment by jcesguerram** [comment]
> +1 on this request!
> 
> In the meantime, I managed to use some of the other Lucide icons by manually putting them in the data.json file in the plugin directory. But this would be 100% better...

how did you do that?

**Comment by O-RONI** [comment]
> how did you do that?

#### 1. Go to `<YOUR VAULT>/.obsidian/plugins/cmdr/data.json`.

#### 2. Search for the _command_ you want to change the icon for

for example, this one: 

![image](https://github.com/phibr0/obsidian-commander/assets/125587006/3e2404dc-b5ce-4228-ace5-7a86080ccbf9)

#### 3. Change the `icon` value for one of the Lucide icons name

You can look for them here: [https://lucide.dev/icons/](https://lucide.dev/icons/)

![image](https://github.com/phibr0/obsidian-commander/assets/125587006/41565ddd-0a95-4da6-b0f7-0da191ec701f)

![image](https://github.com/phibr0/obsidian-commander/assets/125587006/f263d157-a3e6-403e-a3b6-8563c47c4015)


#### 4. Restart Obsidian or the commander plugin for the change to take effect

![image](https://github.com/phibr0/obsidian-commander/assets/125587006/4d253d05-4d64-4400-be7f-c8930de70d74)

**Comment by jcesguerram** [comment]
> > how did you do that?
> 
> #### 1. Go to `<YOUR VAULT>/.obsidian/plugins/cmdr/data.json`.
> #### 2. Search for the _command_ you want to change the icon for
> for example, this one:
> 
> ![image](https://private-user-images.githubusercontent.com/125587006/341574500-3e2404dc-b5ce-4228-ace5-7a86080ccbf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjE1OTgsIm5iZiI6MTcxODkyMTI5OCwicGF0aCI6Ii8xMjU1ODcwMDYvMzQxNTc0NTAwLTNlMjQwNGRjLWI1Y2UtNDIyOC1hY2U1LTdhODYwODBjY2JmOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMjA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02ODA4NDcwNjQ1Y2YxYjk5ZjA0MWUxMTJhN2UyNjY2NDE5ZGQ2NDA5NTZkMDMxOGQ1Yjk4ODRiNTg5YTA3ZDNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GcIacuxu_gNFSTSRU3l_YMJpIjDc4Qw5GSBEGt5btlc)
> 
> #### 3. Change the `icon` value for one of the Lucide icons name
> You can look for them here: https://lucide.dev/icons/
> 
> ![image](https://private-user-images.githubusercontent.com/125587006/341573662-41565ddd-0a95-4da6-b0f7-0da191ec701f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjE1OTgsIm5iZiI6MTcxODkyMTI5OCwicGF0aCI6Ii8xMjU1ODcwMDYvMzQxNTczNjYyLTQxNTY1ZGRkLTBhOTUtNGRhNi1iMGY3LTBkYTE5MWVjNzAxZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMjA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jMWFmOWNhNjZiMGUyMDJhM2VmNjBjNzdiNThlOWIwMTQ1Yzc4Yzk1NThmYTAzZTY1ZDViMzU3YjMyODQ0NjEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.e7EPr5bG009vprDotrHdiZ7KbbsE5of-LbZI68dBtuw)
> 
> ![image](https://private-user-images.githubusercontent.com/125587006/341576454-f263d157-a3e6-403e-a3b6-8563c47c4015.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjE1OTgsIm5iZiI6MTcxODkyMTI5OCwicGF0aCI6Ii8xMjU1ODcwMDYvMzQxNTc2NDU0LWYyNjNkMTU3LWEzZTYtNDAzZS1hM2I2LTg1NjNjNDdjNDAxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMjA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xOTk3NmZhMjg1MmQyYmY2NmM0NzY0YWRiNmI4OTVhMjkxZDg4ODA0Y2ZlNzU2NjdiMjA5N2JjYzE3ZjRhZjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.xhP_U7bLOV2eXDuRkDGstcJ81q5Yqem8MqVFq48dwyQ)
> 
> #### 4. Restart Obsidian or the commander plugin for the change to take effect
> ![image](https://private-user-images.githubusercontent.com/125587006/341576637-4d253d05-4d64-4400-be7f-c8930de70d74.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5MjE1OTgsIm5iZiI6MTcxODkyMTI5OCwicGF0aCI6Ii8xMjU1ODcwMDYvMzQxNTc2NjM3LTRkMjUzZDA1LTRkNjQtNDQwMC1iZTdmLWM4OTMwZGU3MGQ3NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMFQyMjA4MThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lYTgwYjc0Zjg3ZjkyZjI5OGNjN2Q4YTFiMGM3ZWI4ZjBiOThjNGE0NDUxNWVhOWJiNjBmYWZiOWNkNDkyM2M1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.sRHeIwCxkljGklwM3U1vcoBqtVvKpOZrMECPz5svVNE)

oh wow, thanks!

**Comment by erazlogo** [comment]
Thank you [O-RONI](https://github.com/O-RONI)! Worked like a charm.

**Comment by jcesguerram** [comment]
> Thank you @O-RONI! Worked like a charm.

@O-RONI same here! worked great! i really wanted to do that!

**Comment by jsmorabito** [comment]
Hi all, my understanding is that this is done on Obsidian's side. I noticed a request on the forum here if you'd like to upvote it:
https://forum.obsidian.md/t/upgrade-lucide-icons-and-improve-timeliness-of-future-upgrades/73152 

I'd asked about this previously on Discord here (not sure if that link will work):
https://discord.com/channels/686053708261228577/840286264964022302/1217155092256526528

But basically they said they'll update it at some point ¯\_(ツ)_/¯

Thank you @O-RONI for providing a quick fix!

**Comment by albertoloscerritos** [comment]
+1 this would be a great addition 

@okRoni thanks for the workaround

**Comment by jsmorabito** [comment]
This is available with the latest update!

**Comment by albertoloscerritos** [comment]
Thaaaanks
