### ISSUE TITLE
The custom order of commands in the page header does not take effect 

### ISSUE THREAD

**Issue by yejinson** [phibr0/obsidian-commander#13]
### Describe the bug

As the title says, after restarting, it is arranged in some order that I don't understand, and the order I defined cannot be saved.

### Steps to reproduce

Arrange some commands in the page header in a custom order, then close the software and reopen it.

### Operating system

Windows

**Comment by yejinson** [comment]
I just opened the software and found that the order of commands was messed up again, it looked unstable, and there was indeed a problem.

**Comment by yejinson** [comment]
I don't know what happened, it's normal again.

**Comment by phibr0** [comment]
Still seems like undesired behavior, let's keep this issue open!

**Comment by yejinson** [comment]
> Still seems like undesired behavior, let's keep this issue open!

Well, no problem for the last two days, I thought there won't be any more problems. It's best if you can figure out the problem, you can study it, thank you.

**Comment by phibr0** [comment]
Let's track this in #7
