### ISSUE TITLE
Ability to add multiple commands to one button

### ISSUE THREAD

**Issue by batrand** [phibr0/obsidian-commander#17]
### Describe the feature

Ability to add multiple commands into a button, and clicking it will execute all commands assigned to it, maybe in order.

### Does this fix a problem? If so, specify.

My use case is a button to collapse both sidebars. There is a command to toggle the left, another to the right. I want to make a button that will clear out the sidebars instead of having to click two.

**Comment by AtlcatlQ** [comment]
Maybe a hotkey assigned to a macro with QuickAdd or Command Palette++ could solve your problem. Have you considered that?

**Comment by batrand** [comment]
Hey, thanks for the reply. I couldn't find a plugin called Command Palette++, do you mean Better Command Palette? If so, I was able to make a macro and assign it to a Commander button like you said, thanks!

**Comment by AtlcatlQ** [comment]
Yeah, I get the name wrong, but that's the one I meant. I'm glad it helped you :)
