### ISSUE TITLE
Add Commands to File Explorer Top Menu

### ISSUE THREAD

**Issue by iamrecursion** [phibr0/obsidian-commander#2]
### Describe the feature

It would be amazing if commander let you add commands to the menu of buttons at the top of the file explorer.

### Does this fix a problem? If so, specify.

This doesn't fix a problem, but allows more consolidation of plugins.

### Did you consider other alternatives?

There are plugins that can add individual commands there, but it makes sense to manage it globally through this plugin.

**Comment by jsmorabito** [comment]
@iamrecursion thank you for the suggestion, we are looking into this!

**Comment by iamrecursion** [comment]
Amazing! I'm super super looking forward to this! Thanks so much.

**Comment by jsmorabito** [comment]
@iamrecursion by the way, you mentioned adding this feature allows for consolidation of more plugins. Would you mind sharing which plugins you are referring to so we can reach out to the authors/credit them/ let the users of their plugins know that we are offering this feature etc?

**Comment by dolsem** [comment]
[The File Hider plugin](https://github.com/Oliver-Akins/file-hider) would benefit from this feature (they do already mention it in their README but the link goes to the old repository)

**Comment by iamrecursion** [comment]
The particular ones that I had in mind at the time were [collapse all](https://github.com/OfficerHalf/obsidian-collapse-all), which has now been superseded by stock Obsidian, and [reveal active file button](https://github.com/claremacrae/reveal-active-file-button-plugin).

**Comment by jsmorabito** [comment]
released in 0.3.0
