### ISSUE TITLE
I wish I could add commands to the right panel

### ISSUE THREAD

**Issue by PaulHerrero** [phibr0/obsidian-commander#21]
### Describe the feature

I hope it is possible to add commands to the panel on the right side of obsidian. I would like to put commands to adjust markdown formatting here, such as bold, highlight, etc.

### Does this fix a problem? If so, specify.

This helps me edit content more efficiently and easily

### Screenshots and recordings

![image](https://user-images.githubusercontent.com/56058332/189466050-bd8e6323-568b-46ad-b855-5a1d771e2a0f.png)

**Comment by jsmorabito** [comment]
@PaulHerrero thank you for the suggestion! we will look into that as a possible location for commands. in the meantime you might consider looking into this plugin https://github.com/cumany/obsidian-editing-toolbar for your needs

**Comment by PaulHerrero** [comment]
> @PaulHerrero thank you for the suggestion! we will look into that as a possible location for commands. in the meantime you might consider looking into this plugin https://github.com/cumany/obsidian-editing-toolbar for your needs

Thank you for your reply and recommendation. I can now place other commands in this panel.
