### ISSUE TITLE
Only a partial icon list - are some missing?

### ISSUE THREAD

**Issue by trainbuffer** [phibr0/obsidian-commander#22]
### Describe the bug

Setting a custom icon for command seems to have a limited list. Does the icon list really only go from A > C? 

[My goal here is to use the default periodic notes calendar icon with the dots, but it's not in the Commander list] 

<img width="60" alt="1" src="https://user-images.githubusercontent.com/3751726/189503792-fccb28b9-48d9-4be3-b067-1bc3f3ad1e56.png">

### Steps to reproduce

- left ribbon > add command: "Periodic Notes: Open today's daily note"
- a list of different icons is presented starting with "Activity" and ending with "Calendar."
- are there no more options beyond C?

### Operating system

macOS

**Comment by phibr0** [comment]
Obsidian doesn't load them all initially. If you type something in the suggester it will update and show the other icons too.

**Comment by trainbuffer** [comment]
Got it. I'm able to see way more icons now by just typing one letter at a time and scrolling though. 
I thought only seeing A to C was a little suspicious. Thanks.
