### ISSUE TITLE
[Bug]: Tab title bar flickers when switching between side-by-side panes

### ISSUE THREAD

**Issue by pjeby** [phibr0/obsidian-commander#25]
### Describe the bug

If you have panes open side by side on Obsidian 0.16.3, the center breadcrumbs and file name flicker and jump sideways on any change of active pane.

### Steps to reproduce

Open panes side by side on Obsidian 0.16.3, and switch between them.

### Additional context

The issue appears to be due to the updating of items in the tab title bar 1) outside an animation frame and 2) unnecessarily since there has been no change to the buttons.  It isn't actually necessary to recreate the buttons on every file-open event, as the buttons are only removed when the view object is replaced -- you could probably just use a WeakSet of leaf.view instances and call view.addAction() to add the buttons when you see a view that's not in the WeakSet.  (Or a weakmap to a list of the added elements, so they can be removed if needed.)  This would avoid changing the buttons when the view itself isn't changed.

Let me know if you'd like me to make a pull request for this.

### Operating system

Windows

**Comment by phibr0** [comment]
If you have the time to make a PR for this, I'd be very happy!  I will also try and fix some of the other issues, but just don't have enough time atm.

**Comment by pjeby** [comment]
Ok, PR #26 fixes this and a bunch of other pending stuff with the page headers.  Hope you find it useful.

**Comment by phibr0** [comment]
Definetly! Thanks a lot
