### ISSUE TITLE
Add support for new mobile bar/left ribbon replacement

### ISSUE THREAD

**Issue by lguenth** [phibr0/obsidian-commander#29]
### Describe the feature

Hey Phillip,
I hope you're doing well! With the new public release, I thought I might ask about a feature I'd like to see in the mobile app.

I would love if the settings for the left ribbon would now be applied to its new replacement in the mobile app, the long press menu on the right of the "tool bar" (next to the tab switcher).

Do you think this is possible?

### Does this fix a problem? If so, specify.

I think that this would be a nice addition to the plugin as it would bring the functionality on par with the desktop experience. Many people on Discord have asked about it as well.

### Did you consider other alternatives?

There aren't really any alternatives. The left ribbon settings are currently useless on mobile and I don't know of any other plugin which modifies that list of commands.

### Screenshots and recordings

I'll clarify the position in the tool bar with two screenshots in a few minutes. Okay, for anyone else reading this, this is the button I'm talking about:
<img src="https://user-images.githubusercontent.com/69049131/196003502-c6f8e73a-6c9f-4a9d-9e06-132be294a125.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/69049131/196003513-d0b4a14c-7f55-46ef-96ad-94443b57b9cc.png" width=50% height=50%>

**Comment by phibr0** [comment]
Yes, that is definitely something I will be working on! Stay tuned for the next update 👀

**Comment by brimwats** [comment]
also just confirming that this doesn't work on android but mostly so I get the notification when it's solved! :)

**Comment by MystreAqui** [comment]
I miss the left ribbon 😞

**Comment by leoccyao** [comment]
Has been following this issue for a while, and updated to 0.3.0 as soon as I heard (the number of plugins I have installed has made my mobile toolbar basically unusable). However, even testing on a fresh vault, I wasn't able to get commands hidden:

![image](https://user-images.githubusercontent.com/45076643/198865924-a4a58a17-93b3-4312-ba1d-e43c3bbe57bb.jpeg)
![image](https://user-images.githubusercontent.com/45076643/198865927-3c0eb533-2408-4d64-819a-3e07745c9fc5.jpeg)

iOS 15, Obsidian Mobile v1.4.1, tested on a fresh vault.

**Comment by brimwats** [comment]
seconded, we may need a new issue created

**Comment by tonyxiao** [comment]
Alternatively if I can at least order the custom commands up top that will already be super useful #10 (related)

**Comment by tonyxiao** [comment]
Can be a good workaround until this is fixed.

**Comment by tonyxiao** [comment]
and perhaps a useful feature of itself

**Comment by trainbuffer** [comment]
Is v3.0 supposed to address adding/hiding on the new mobile(phone) ribbon on the bottom right? Adding commands to the ribbon works for me, but can't hide the defaults (and therefore can't order properly). (?_?)

**Comment by brimwats** [comment]
y'all, we should make new issues. lots of creators don't have notifications on old issues. highly recommend new issues.

**Comment by phibr0** [comment]
> y'all, we should make new issues. lots of creators don't have notifications on old issues. highly recommend new issues.

I do read all the issues! I just don't have enough time to work on Commander at the moment. If someone knows a fix for this, I would greatly appreciate a PR, otherwise it might take a few more weeks
