### ISSUE TITLE
[Bug]: ribbon "hide other commands" is empty

### ISSUE THREAD

**Issue by Alex-coder251** [phibr0/obsidian-commander#40]
### Describe the bug

![image](https://user-images.githubusercontent.com/58896036/199463551-dcc2fb33-5d23-4a10-8583-60ce762f238b.png)
As the title indicates,  i have reinstall many times. 😭

### Steps to reproduce

open settings menu

### Operating system

Windows

**Comment by phibr0** [comment]
Thats weird. Can you open the Console and look for errors? You can open it by pressing <kbd>ctrl</kbd> + <kbd>shift</kbd> + <kbd>i</kbd>

**Comment by Alex-coder251** [comment]
> Thats weird. Can you open the Console and look for errors? You can open it by pressing ctrl + shift + i

Uncaught TypeError: Cannot read properties of null
![image](https://user-images.githubusercontent.com/58896036/199466129-a43b6f98-e296-4efd-a47b-9cea848ecfdc.png)
