### ISSUE TITLE
Changing new mobile toolbar

### ISSUE THREAD

**Issue by matejdro** [phibr0/obsidian-commander#54]
### Describe the feature

With the recent tabs update, mobile toolbar changed to this five button layout:

![image](https://user-images.githubusercontent.com/507922/205427957-511981f7-0d05-4a64-a069-97020c2a5b9c.png)

It seems like Commander can't change this toolbar? 

### Does this fix a problem? If so, specify.

Same problem as previous toolbar - it would allow users to customize the icons there.

**Comment by ChrisDoohan** [comment]
This looks like a duplicate of #43

**Comment by matejdro** [comment]
Yup, it is.
