### ISSUE TITLE
[Bug]: Custom ribbon commands disappear when using standard ribbon commands (Insider v1.1.0)

### ISSUE THREAD

**Issue by 23maverick23** [phibr0/obsidian-commander#57]
### Describe the bug

When using custom ribbon commands, they initially appear in the ribbon, however upon clicking standard command buttons like "Open graph view" or "Open command palette", the custom commands disappear. You can get them back with a "Force refresh", but that seems to be the only "fix", and it is temporary.

### Relevant errors (if available)

```Shell
// with debugging enabled in plugin settings, nothing prints to the console for this plugin
// no other errors from conflicting plugins display either
```

### Steps to reproduce

1. Enable one or more standard ribbon commands (e.g. "Open graph view" and "Open command palette")
2. Create custom ribbon commands and add them to the ribbon
3. Click on one or both of the standard command buttons
4. Use the "Force refresh" menu to bring the custom commands back

### Expected Behavior

Custom buttons were persistent before the v1.1.0 Obsidian release. This new behavior likely has to do with the new abilities to customize the ribbon natively without cmdr plugin.

### Additional context

macOS v12.6.1
Obsidian.md v1.1.0
    Installer v1.0.3
cmdr v0.4.4

### Operating system

macOS

**Comment by tecnoborder** [comment]
Same issue

**Comment by phibr0** [comment]
Can reproduce, will work on it next week!
