### ISSUE TITLE
Suggest to optimize macro autorun

### ISSUE THREAD

**Issue by StrollStars** [phibr0/obsidian-commander#60]
### Describe the feature

https://github.com/phibr0/obsidian-commander/issues/51 has been realized.
But in use, I found that its processing is a bit slow. I can see the process of macro operation after the program is started, and I hope that the process can be completed before Obsidian's interface is displayed.

### Does this fix a problem? If so, specify.

No

### Did you consider other alternatives?

[QuickAdd](https://github.com/chhoumann/quickadd) can be done.

**Comment by phibr0** [comment]
Hm not sure how this works in quickadd. But Commander has to wait for all other Plugins to be initialized befote it can run its startup macros, as they could contain commands by those Plugins

**Comment by StrollStars** [comment]
@phibr0 That is to say, the more plugins are installed, the slower the macro starts?

**Comment by phibr0** [comment]
Kindof yeah, the macros wait for the interface to be usable, because at that point all plugins have finished loading.

**Comment by StrollStars** [comment]
@phibr0 Thank you for your explanation, I use [QuickAdd](https://github.com/chhoumann/quickadd) instead temporarily.
