### ISSUE TITLE
[Bug]: Tab bar icons not retaining their position 

### ISSUE THREAD

**Issue by daxmonson** [phibr0/obsidian-commander#78]
### Describe the bug

Tab bar icons not saving state set by user. 

### Steps to reproduce

Sort icons on tab bar as needed, go about day, eventually tab icons shuffle to positions not set by user. This happened on an old ios device and also on a fresh install on another. 

### Expected Behavior

Tab bar icons should retain position through Obsidian sessions.

### Additional context

Have some mission critical commands in the tab icon area. When ios devices have Obsidian in slide-over mode the important icons can't be seen/accessed as they've moved all the way to the right off the tiny tab area when Obsidian is in slide-over. It's an essential and great add-on, hope you can take a look. Thanks!

### Operating system

iOS

**Comment by samaellain** [comment]
I have the same problem in windows 11.

**Comment by samaellain** [comment]
temporary workaround: Toggle the options for desktop or mobile only and the position stick.

**Comment by daxmonson** [comment]
Something about the latest insider build of Obs sorted this and it's now working properly.
