### ISSUE TITLE
[Bug]: Some plugin commands are missing

### ISSUE THREAD

**Issue by chenxin0397** [phibr0/obsidian-commander#9]
### Describe the bug

I set 5 commands before, now there are only 4 left, but there are only 3 commands in the settings panel

### Steps to reproduce

![202108161359350001001](https://user-images.githubusercontent.com/73974352/182059314-974c37fb-dae7-47fb-a3a0-7b6ce25c5406.gif)

### Operating system

Windows

**Comment by phibr0** [comment]
Can you send me your `data.json` file inside the plugin's directory? It is located in `<vault folder>/.obsidian/plugin/cmdr/data.json`

**Comment by chenxin0397** [comment]
{
  "confirmDeletion": false,
  "showAddCommand": true,
  "debug": false,
  "editorMenu": [
    {
      "id": "workspaces-plus:常用工作区",
      "icon": "layout-dashboard",
      "name": "Workspaces Plus: Load: 常用工作区",
      "mode": "any"
    },
    {
      "id": "file-explorer:reveal-active-file",
      "icon": "folder-open",
      "name": "文件列表: 在文件列表中显示当前文件",
      "mode": "any"
    },
    {
      "id": "starred:open",
      "icon": "star-glyph",
      "name": "星标: 显示星标标签页",
      "mode": "any"
    },
    {
      "id": "obsidian-quiet-outline:quiet-outline",
      "icon": "list",
      "name": "Quiet Outline: Quiet Outline",
      "mode": "any"
    },
    {
      "id": "cm-typewriter-scroll-obsidian:toggle-typewriter-sroll",
      "icon": "align-vertical-space-around",
      "name": "Typewriter Scroll: Toggle On/Off",
      "mode": "any"
    },
    {
      "id": "workspace:open-in-new-window",
      "icon": "fullscreen",
      "name": "在新窗口中打开当前面板",
      "mode": "any"
    }
  ],
  "fileMenu": [],
  "leftRibbon": [],
  "rightRibbon": [],
  "titleBar": [
    {
      "id": "obsidian-hover-editor:convert-active-pane-to-popover",
      "icon": "inspect",
      "name": "Hover Editor: Convert active pane to Hover Editor",
      "mode": "any"
    },
    {
      "id": "editor:toggle-numbered-list",
      "icon": "number-list-glyph",
      "name": "有序列表",
      "mode": "any"
    },
    {
      "id": "Enhanced-editing:add-daima",
      "icon": "code-2",
      "name": "增强编辑: ```代码块```",
      "mode": "any"
    }
  ],
  "statusBar": [],
  "pageHeader": [
    {
      "id": "workspaces-plus:常用工作区",
      "icon": "layout-dashboard",
      "name": "Workspaces Plus: Load: 常用工作区",
      "mode": "any"
    },
    {
      "id": "app:toggle-left-sidebar",
      "icon": "chevron-left",
      "name": "折叠/展开左侧边栏",
      "mode": "any"
    },
    {
      "id": "file-explorer:reveal-active-file",
      "icon": "navigate-glyph",
      "name": "文件列表: 在文件列表中显示当前文件",
      "mode": "any"
    },
    {
      "id": "theme:use-light",
      "icon": "sun",
      "name": "使用浅色模式",
      "mode": "any"
    },
    {
      "id": "theme:use-dark",
      "icon": "moon",
      "name": "使用深色模式",
      "mode": "any"
    },
    {
      "id": "workspace:split-vertical",
      "icon": "vertical-split",
      "name": "左右拆分",
      "mode": "any"
    },
    {
      "id": "workspace:split-horizontal",
      "icon": "horizontal-split",
      "name": "上下拆分",
      "mode": "any"
    },
    {
      "id": "obsidian-hover-editor:open-new-popover",
      "icon": "box-select",
      "name": "Hover Editor: Open new Hover Editor",
      "mode": "any"
    },
    {
      "id": "quickadd:choice:6ec6d567-bc23-4241-ae83-b48fe203ab8e",
      "icon": "codesandbox",
      "name": "QuickAdd: 🗂 QuickAdd-命令集",
      "mode": "any"
    }
  ],
  "macros": [],
  "hide": {
    "statusbar": [
      "various-complements"
    ],
    "leftRibbon": [
      "打开 Markdown 格式转换器",
      "Templater",
      "打开命令面板",
      "查看关系图谱",
      "打开快速切换"
    ]
  },
  "spacing": "8"
}

**Comment by chenxin0397** [comment]
Missing the following code
title bar
    {
      "id": "obsidian-title-serial-number-plugin:set-title-serial-number-editor-command",
      "icon": "type",
      "name": "Title Serial Number Plugin: Set Serial Number For Title",
      "mode": "any"
    },
    {
      "id": "obsidian-title-serial-number-plugin:clear-title-serial-number-editor-command",
      "icon": "equal-not",
      "name": "Title Serial Number Plugin: Clear Serial Number For Title",
      "mode": "any"
    }

**Comment by chenxin0397** [comment]
It should be that "Titlebar" is unstable. After adding some new commands, it will fail after closing the OB twice.
